<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Background_Quest_Resolution.png" />
    <None Remove="Background_State.png" />
    <None Remove="Background_Top.png" />
    <None Remove="Fadriass.png" />
    <None Remove="Fùchóu.png" />
    <None Remove="Quest_Fadriass.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Background_Quest_Resolution.png" />
    <Resource Include="Background_State.png" />
    <Resource Include="Background_Top.png" />
    <Resource Include="Fadriass.png" />
    <Resource Include="Fùchóu.png" />
    <Resource Include="Quest_Fadriass.png" />
  </ItemGroup>

</Project>
