<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\Personnages\Aventuriers-Spéciaux\Fùchóu.png" />
    <None Remove="assets\Personnages\Aventuriers-Spéciaux\Hēi Jiǔ.png" />
    <None Remove="assets\Personnages\Aventuriers-Spéciaux\Zhìyuān.png" />
    <None Remove="assets\Personnages\Aventuriers\Profile_HBarabarian1.png" />
    <None Remove="assets\Personnages\Aventuriers\Profile_HMage1.png" />
    <None Remove="assets\Personnages\Aventuriers\Profile_HPriest1.png" />
    <None Remove="assets\Personnages\Aventuriers\Profile_HRanger1.png" />
    <None Remove="assets\Personnages\Aventuriers\Profile_HRogue1.png" />
    <None Remove="assets\Personnages\Aventuriers\Profile_HTank1.png" />
    <None Remove="assets\Personnages\Aventuriers\Profile_HWarrior1.png" />
    <None Remove="assets\Personnages\Personnages-Importants\Fadriass.png" />
    <None Remove="assets\Personnages\Personnages-Importants\Meurtrier.png" />
    <None Remove="assets\UI\Background\Background_Adventurer.png" />
    <None Remove="assets\UI\Background\Background_Quest.png" />
    <None Remove="assets\UI\Background\Background_Quest_Resolution.png" />
    <None Remove="assets\UI\Background\Background_State.png" />
    <None Remove="assets\UI\Background\Background_Top.png" />
    <None Remove="assets\UI\Icon\Gold_Icon.png" />
    <None Remove="assets\UI\Icon\Level_Icon.png" />
    <None Remove="assets\UI\Quest_Illustrations\Quest_Circle.png" />
    <None Remove="assets\UI\Quest_Illustrations\Quest_Dragon.png" />
    <None Remove="assets\UI\Quest_Illustrations\Quest_Fadriass.png" />
    <None Remove="assets\UI\Quest_Illustrations\Quest_Goblins.png" />
    <None Remove="assets\UI\Quest_Illustrations\Quest_Spiders.png" />
    <None Remove="assets\UI\Quest_Illustrations\Quest_Trees.png" />
    <None Remove="assets\UI\Quest_Illustrations\Quest_Zombies.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\Personnages\Aventuriers-Spéciaux\Fùchóu.png" />
    <Resource Include="assets\Personnages\Aventuriers-Spéciaux\Hēi Jiǔ.png" />
    <Resource Include="assets\Personnages\Aventuriers-Spéciaux\Zhìyuān.png" />
    <Resource Include="assets\Personnages\Aventuriers\Profile_HBarabarian1.png" />
    <Resource Include="assets\Personnages\Aventuriers\Profile_HMage1.png" />
    <Resource Include="assets\Personnages\Aventuriers\Profile_HPriest1.png" />
    <Resource Include="assets\Personnages\Aventuriers\Profile_HRanger1.png" />
    <Resource Include="assets\Personnages\Aventuriers\Profile_HRogue1.png" />
    <Resource Include="assets\Personnages\Aventuriers\Profile_HTank1.png" />
    <Resource Include="assets\Personnages\Aventuriers\Profile_HWarrior1.png" />
    <Resource Include="assets\Personnages\Personnages-Importants\Fadriass.png" />
    <Resource Include="assets\Personnages\Personnages-Importants\Meurtrier.png" />
    <Resource Include="assets\UI\Background\Background_Adventurer.png" />
    <Resource Include="assets\UI\Background\Background_Quest.png" />
    <Resource Include="assets\UI\Background\Background_Quest_Resolution.png" />
    <Resource Include="assets\UI\Background\Background_State.png" />
    <Resource Include="assets\UI\Background\Background_Top.png" />
    <Resource Include="assets\UI\Icon\Gold_Icon.png" />
    <Resource Include="assets\UI\Icon\Level_Icon.png" />
    <Resource Include="assets\UI\Quest_Illustrations\Quest_Circle.png" />
    <Resource Include="assets\UI\Quest_Illustrations\Quest_Dragon.png" />
    <Resource Include="assets\UI\Quest_Illustrations\Quest_Fadriass.png" />
    <Resource Include="assets\UI\Quest_Illustrations\Quest_Goblins.png" />
    <Resource Include="assets\UI\Quest_Illustrations\Quest_Spiders.png" />
    <Resource Include="assets\UI\Quest_Illustrations\Quest_Trees.png" />
    <Resource Include="assets\UI\Quest_Illustrations\Quest_Zombies.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
